### ISSUE TITLE
NetWorkCenter bug

### ISSUE THREAD

**Issue by wszyquan** [sd4324530/fastweixin#15]
源码
============
 public static BaseResponse post(String url, String paramData, List<File> fileList) {
        final BaseResponse[] response = new BaseResponse[]{null};
        post(url, paramData, fileList, new ResponseCallback() {
            @Override
            public void onResponse(int resultCode, String resultJson) {
                if (200 == resultCode) {
                    BaseResponse r = JSONUtil.toBean(resultJson, BaseResponse.class);
                    if(StrUtil.isBlank(r.getErrcode())) {
                        r.setErrcode("0");
                    }
                    r.setErrmsg(resultJson);
                    response[0] = r;
                } else {//请求本身就失败了
                    response[0] = new BaseResponse();
                    response[0].setErrcode(String.valueOf(resultCode));
                    response[0].setErrmsg("请求失败");
                }
            }
        });
        return response[0];
    }

当请求失败的时候errmsg为"请求失败"，导致外层API调用时，在请求异常时，json解析失败
例如 BaseResponse r = executePost(url, null, file);
        response = JSONUtil.toBean(r.getErrmsg(), UploadMediaResponse.class);

可以将上面的请求失败的时候errmsg设置成返回数据，方法2，在所有调用的api处，检查errcode分别处理正常和异常的情况

**Comment by sd4324530** [comment]
这个问题修复了，是API接入写法漏写的一行判断，节后发布新版
感谢反馈！
