### ISSUE TITLE
微信服务器绑定验证失败，返回给官方的响应应设置为xml格式

### ISSUE THREAD

**Issue by immime** [sd4324530/fastweixin#8]
验证token、appid、appsecret都通过，代码也返回true，但是微信开发者服务器绑定却总提示失败，排查后的解决方案是：
com.github.sd4324530.fastweixin.servlet.WeixinControllerSupport:line 27加上
(produces = "application/xml;charset=UTF-8")

**Comment by sd4324530** [comment]
已经加上，1.3.5版本开始可以解决这个问题
